---
name: Add New Issues To Innovation Solution Engineering project

permissions: read-all

"on":
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: uhg-runner
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/optum-omnichannel/projects/14
          github-token: ${{ secrets.ISE_BOT_PAT }}
